/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import model.DaoDog;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;
import org.jfree.chart.plot.PlotOrientation;


public class TelaDashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     * 
     **/
    DaoDog daodog;
   
    public TelaDashboard(){
        initComponents();
        daodog = new DaoDog();
        Integer clientes = daodog.verTodos().size();
        Integer petsMachos = daodog.buscarPetsMachos().size();
        Integer petsFemeas = daodog.buscarPetsFemeas().size();
        jLabel4.setText("Total de clientes Cadastrados: " + clientes.toString());
        jLabel8.setText("Total de pets machos: " + petsMachos.toString());
        jLabel9.setText("Total de pets femeas: " + petsFemeas.toString());
        jLabe20.setText("Total de pets consultados:" + clientes.toString());
        showPieChart();
        showLineChart();
    }
    
    public final void showPieChart(){
        
      DefaultPieDataset barDataset = new DefaultPieDataset( );
      barDataset.setValue( "Normal" ,( daodog.buscarUserNormal().size() ) );    
      barDataset.setValue( "Conveniado" ,(daodog.buscarUserConvenio().size() ) );  
      barDataset.setValue( "Plano Dog Counter" , ( daodog.buscarUserPlanoDogCounter().size()) );
      
      JFreeChart piechart = ChartFactory.createPieChart("Tipos de Planos",barDataset, false,true,false);//explain
      
       PiePlot piePlot =(PiePlot) piechart.getPlot();
 
       piePlot.setSectionPaint("Normal", new Color(255,255,102));
       piePlot.setSectionPaint("Conveniado", new Color(102,255,102));
       piePlot.setSectionPaint("Plano Dog Counter", new Color(255,102,153));
      
       piePlot.setBackgroundPaint(Color.white);
        
        ChartPanel barChartPanel = new ChartPanel(piechart);
        grafico1.removeAll();
        grafico1.add(barChartPanel, BorderLayout.CENTER);
        grafico1.validate();
    }
    
    public void showLineChart(){
        
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        dataset.setValue(daodog.buscarUserMasculino().size(), "Cadastros", "Masculino");
        dataset.setValue(daodog.buscarUserFeminino().size(), "Cadastros", "Feminino");
        dataset.setValue(daodog.buscarUserOutros().size(), "Cadastros", "Outros");
        dataset.setValue(daodog.buscarUserNi().size(), "Cadastros", "Não Informado");
        
        JFreeChart linechart = ChartFactory.createLineChart("Cadastros Mensais","Tipo","Cadastros", 
                dataset,PlotOrientation.VERTICAL, false,true,false);
        
        CategoryPlot lineCategoryPlot = linechart.getCategoryPlot();

        lineCategoryPlot.setBackgroundPaint(Color.white);

        LineAndShapeRenderer lineRenderer = (LineAndShapeRenderer) lineCategoryPlot.getRenderer();
        Color lineChartColor = new Color(204,0,51);
        lineRenderer.setSeriesPaint(0, lineChartColor);
        
        ChartPanel lineChartPanel = new ChartPanel(linechart);
        grafico2.removeAll();
        grafico2.add(lineChartPanel, BorderLayout.CENTER);
        grafico2.validate();
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnRelatorio = new javax.swing.JButton();
        btnCadastrarVeiculo = new javax.swing.JButton();
        btFinanceiro = new javax.swing.JButton();
        btConf = new javax.swing.JButton();
        btLogout = new javax.swing.JButton();
        grafico1 = new javax.swing.JPanel();
        grafico2 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        grafico3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabe20 = new javax.swing.JLabel();
        grafico4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        grafico5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        grafico6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(249, 233, 210));

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(73, 49, 31));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dog Counter");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/cachorro100px.png"))); // NOI18N

        btnRelatorio.setBackground(new java.awt.Color(73, 49, 31));
        btnRelatorio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnRelatorio.setForeground(new java.awt.Color(73, 49, 31));
        btnRelatorio.setText("Relatório/Consulta");
        btnRelatorio.setBorderPainted(false);
        btnRelatorio.setContentAreaFilled(false);
        btnRelatorio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        btnCadastrarVeiculo.setBackground(new java.awt.Color(73, 49, 31));
        btnCadastrarVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCadastrarVeiculo.setForeground(new java.awt.Color(73, 49, 31));
        btnCadastrarVeiculo.setText("Cadastrar Pet");
        btnCadastrarVeiculo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCadastrarVeiculo.setBorderPainted(false);
        btnCadastrarVeiculo.setContentAreaFilled(false);
        btnCadastrarVeiculo.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCadastrarVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarVeiculoActionPerformed(evt);
            }
        });

        btFinanceiro.setBackground(new java.awt.Color(73, 49, 31));
        btFinanceiro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btFinanceiro.setForeground(new java.awt.Color(73, 49, 31));
        btFinanceiro.setText("Financeiro");
        btFinanceiro.setBorderPainted(false);
        btFinanceiro.setContentAreaFilled(false);
        btFinanceiro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinanceiroActionPerformed(evt);
            }
        });

        btConf.setBackground(new java.awt.Color(73, 49, 31));
        btConf.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btConf.setForeground(new java.awt.Color(73, 49, 31));
        btConf.setText("Configurações");
        btConf.setBorderPainted(false);
        btConf.setContentAreaFilled(false);
        btConf.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btConf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btConfActionPerformed(evt);
            }
        });

        btLogout.setBackground(new java.awt.Color(73, 49, 31));
        btLogout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btLogout.setForeground(new java.awt.Color(73, 49, 31));
        btLogout.setText("Logout");
        btLogout.setBorderPainted(false);
        btLogout.setContentAreaFilled(false);
        btLogout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btFinanceiro)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btLogout)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addComponent(jLabel1))
                            .addComponent(btConf)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnRelatorio)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnCadastrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(77, 77, 77)
                .addComponent(btnCadastrarVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRelatorio)
                .addGap(18, 18, 18)
                .addComponent(btFinanceiro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                .addComponent(btConf)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btLogout)
                .addContainerGap())
        );

        grafico1.setBackground(new java.awt.Color(255, 255, 255));
        grafico1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        grafico1.setLayout(new java.awt.BorderLayout());

        grafico2.setBackground(new java.awt.Color(255, 255, 255));
        grafico2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        grafico2.setLayout(new java.awt.BorderLayout());

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 60)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(73, 49, 31));
        jLabel12.setText("Dashboard");

        grafico3.setBackground(new java.awt.Color(185, 106, 35));
        grafico3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        grafico3.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel7.setText("Pets Consultados");
        grafico3.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jLabe20.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabe20.setForeground(new java.awt.Color(255, 255, 255));
        grafico3.add(jLabe20, java.awt.BorderLayout.LINE_START);

        grafico4.setBackground(new java.awt.Color(185, 106, 35));
        grafico4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        grafico4.setLayout(new java.awt.BorderLayout());

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel6.setText("Pets Femeas");
        grafico4.add(jLabel6, java.awt.BorderLayout.PAGE_START);

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        grafico4.add(jLabel9, java.awt.BorderLayout.LINE_START);

        grafico5.setBackground(new java.awt.Color(249, 233, 210));
        grafico5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        grafico5.setLayout(new java.awt.BorderLayout());

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel5.setText("Pets Machos");
        grafico5.add(jLabel5, java.awt.BorderLayout.PAGE_START);

        jLabel8.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        grafico5.add(jLabel8, java.awt.BorderLayout.LINE_START);

        grafico6.setBackground(new java.awt.Color(249, 233, 210));
        grafico6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        grafico6.setLayout(new java.awt.BorderLayout());

        jLabel3.setBackground(new java.awt.Color(249, 233, 210));
        jLabel3.setFont(new java.awt.Font("sansserif", 0, 24)); // NOI18N
        jLabel3.setText("Clientes");
        grafico6.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jLabel4.setBackground(new java.awt.Color(249, 233, 210));
        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        grafico6.add(jLabel4, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(grafico6, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(grafico3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grafico1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(grafico2, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(grafico4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(grafico5, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grafico3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(grafico6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(grafico4, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(grafico1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(grafico2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(grafico5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarVeiculoActionPerformed
        TelaCadastroPet telaCadastro = new TelaCadastroPet();
        this.dispose();
        telaCadastro.setVisible(true);
    }//GEN-LAST:event_btnCadastrarVeiculoActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioActionPerformed
        TelaRelatorio telaRelatorio = new TelaRelatorio();
        this.dispose();
        telaRelatorio.setVisible(true);
    }//GEN-LAST:event_btnRelatorioActionPerformed

    private void btFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinanceiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btFinanceiroActionPerformed

    private void btConfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btConfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btConfActionPerformed

    private void btLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btConf;
    private javax.swing.JButton btFinanceiro;
    private javax.swing.JButton btLogout;
    private javax.swing.JButton btnCadastrarVeiculo;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JPanel grafico1;
    private javax.swing.JPanel grafico2;
    private javax.swing.JPanel grafico3;
    private javax.swing.JPanel grafico4;
    private javax.swing.JPanel grafico5;
    private javax.swing.JPanel grafico6;
    private javax.swing.JLabel jLabe20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
